### ISSUE TITLE
How can I make multiple servers sharing a single HTTP/S server

### ISSUE THREAD

**Issue by cage1618** [fastify/fastify-websocket#240]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the issue has not already been raised

### Issue

I want to make multiple servers sharing a single HTTP/S server? Beause I use yaml configure my routers like blew code:
```yaml
GET /ws/chat:
  handler: controllers/ws.chat
  websocket: true
  verifyClient: hooks/chat-pre-connect

# another router
GET /ws/notice:
  handler: controllers/ws.notice
  websocket: true
  verifyClient: hooks/notice-pre-connect
```

Then I will lookup the route config, everytime will run:
```javascript
fastify.register(require('@fastify/websocket'), {
  options: {
    verifyClient: require('which file specified  by the verifyClient field on the route ')
  }
})

fastify.route({
  ...the route config,
  handler: the method in the file specified  by the handler field on the route
})
```

But I caught a error:
```shell
Error [ERR_INTERNAL_ASSERTION]: This is caused by either a bug in Node.js or incorrect usage of Node.js internals.
Please open an issue with this stack trace at https://github.com/nodejs/node/issues
  at new NodeError (node:internal/errors:393:5)
  at assert (node:internal/assert:14:11)
  at ServerResponse.assignSocket (node:_http_server:279:3)
  at Server.<anonymous> (/the-project-path/node_modules/@fastify/websocket/index.js:54:19)
  at Server.emit (node:events:525:35)
  at Server.<anonymous> (/Users/hkk/.nvm/versions/node/v18.8.0/lib/node_modules/pm2/node_modules/@pm2/io/build/main/metrics/httpMetrics.js:152:37)
  at onParserExecuteCommon (node:_http_server:846:14)
  at onParserExecute (node:_http_server:760:3)
```

How can I fix it? Thanks!
